export const testimonials = [
  // --- Família (16 itens) ---
  {
    id: 101,
    category: "Família",
    quote: "A Clausify revolucionou a forma como lidamos com processos de divórcio. A organização é impecável.",
    author: "Dra. Ana Paula Souza",
    role: "Especialista em Direito de Família",
    image: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    id: 102,
    category: "Família",
    quote: "Consigo acompanhar dezenas de casos de guarda simultaneamente sem perder nenhum prazo. Incrível.",
    author: "Dr. Marcos Vinícius",
    role: "Advogado de Família",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 103,
    category: "Família",
    quote: "A automação de documentos para pensão alimentícia me poupou horas de trabalho manual.",
    author: "Dra. Juliana Martins",
    role: "Sócia - Martins & Associados",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 104,
    category: "Família",
    quote: "Meus clientes se sentem mais seguros com a agilidade que a plataforma proporciona nos processos de inventário.",
    author: "Dr. Roberto Carlos",
    role: "Advogado Sênior",
    image: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    id: 105,
    category: "Família",
    quote: "A interface é intuitiva e perfeita para gerenciar mediações familiares complexas.",
    author: "Dra. Fernanda Lima",
    role: "Mediadora Familiar",
    image: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    id: 106,
    category: "Família",
    quote: "O suporte da Clausify é excelente, sempre prontos para ajudar com as especificidades do direito de família.",
    author: "Dr. André Santos",
    role: "Advogado",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 107,
    category: "Família",
    quote: "Reduzi o tempo de resposta aos clientes em 50% graças à organização da plataforma.",
    author: "Dra. Camila Rocha",
    role: "Especialista em Sucessões",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: 108,
    category: "Família",
    quote: "Ferramenta indispensável para quem atua com direito de família e precisa de sensibilidade e eficiência.",
    author: "Dr. Paulo Henrique",
    role: "Advogado",
    image: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    id: 109,
    category: "Família",
    quote: "A gestão de documentos digitalizados facilitou muito o acesso às certidões e provas.",
    author: "Dra. Luiza Pereira",
    role: "Sócia Fundadora",
    image: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    id: 110,
    category: "Família",
    quote: "Nunca mais perdi uma audiência de conciliação. O sistema de alertas é perfeito.",
    author: "Dr. Gustavo Oliveira",
    role: "Advogado de Família",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 111,
    category: "Família",
    quote: "A Clausify trouxe modernidade para o meu escritório de advocacia familiar.",
    author: "Dra. Beatriz Costa",
    role: "Advogada",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    id: 112,
    category: "Família",
    quote: "Eficiência e praticidade. Tudo o que eu precisava para escalar meu atendimento em direito de família.",
    author: "Dr. Rafael Almeida",
    role: "Sócio",
    image: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    id: 113,
    category: "Família",
    quote: "O módulo financeiro integrado ajuda muito na cobrança de honorários em casos de longo prazo.",
    author: "Dra. Patrícia Silva",
    role: "Gestora Jurídica",
    image: "https://randomuser.me/api/portraits/women/7.jpg",
  },
  {
    id: 114,
    category: "Família",
    quote: "Recomendo para todos os colegas que atuam na área de família e sucessões.",
    author: "Dr. Thiago Ferreira",
    role: "Advogado",
    image: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 115,
    category: "Família",
    quote: "A segurança dos dados dos clientes é um diferencial que prezo muito, e a Clausify garante isso.",
    author: "Dra. Mariana Dias",
    role: "Advogada Sênior",
    image: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    id: 116,
    category: "Família",
    quote: "Facilitou a comunicação com a equipe e a distribuição de tarefas nos casos de adoção.",
    author: "Dr. Lucas Mendes",
    role: "Advogado",
    image: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 117,
    category: "Família",
    quote: "A organização de documentos de divórcio nunca foi tão simples e segura.",
    author: "Dr. Roberto Dias",
    role: "Advogado de Família",
    image: "https://randomuser.me/api/portraits/men/50.jpg",
  },
  {
    id: 118,
    category: "Família",
    quote: "O módulo de agenda me ajuda a não perder nenhuma audiência de custódia.",
    author: "Dra. Camila Nunes",
    role: "Especialista em Família",
    image: "https://randomuser.me/api/portraits/women/50.jpg",
  },
  {
    id: 119,
    category: "Família",
    quote: "Excelente para escritórios que lidam com alto volume de pensões alimentícias.",
    author: "Dr. Felipe Costa",
    role: "Sócio",
    image: "https://randomuser.me/api/portraits/men/51.jpg",
  },
  {
    id: 120,
    category: "Família",
    quote: "A Clausify trouxe a paz de espírito que eu precisava para gerir meu escritório.",
    author: "Dra. Larissa Silva",
    role: "Advogada",
    image: "https://randomuser.me/api/portraits/women/51.jpg",
  },
  {
    id: 121,
    category: "Família",
    quote: "Ferramenta essencial para mediação e conciliação familiar.",
    author: "Dr. Gustavo Alves",
    role: "Mediador",
    image: "https://randomuser.me/api/portraits/men/52.jpg",
  },

  // --- Cível e Bancário (16 itens) ---
  {
    id: 201,
    category: "Cível e Bancário",
    quote: "A análise de contratos bancários ficou muito mais rápida com as ferramentas de IA da Clausify.",
    author: "Dr. Ricardo Gomes",
    role: "Especialista em Direito Bancário",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    id: 202,
    category: "Cível e Bancário",
    quote: "Gerenciar milhares de ações de massa nunca foi tão simples. O painel é muito visual.",
    author: "Dra. Vanessa Lopes",
    role: "Gerente Jurídico",
    image: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 203,
    category: "Cível e Bancário",
    quote: "O controle de prazos processuais no cível é infalível. Durmo tranquilo.",
    author: "Dr. Fernando Torres",
    role: "Sócio - Torres Advogados",
    image: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    id: 204,
    category: "Cível e Bancário",
    quote: "A automação de peças processuais repetitivas aumentou nossa produtividade em 300%.",
    author: "Dra. Cláudia Nunes",
    role: "Coordenadora Cível",
    image: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    id: 205,
    category: "Cível e Bancário",
    quote: "Excelente para lidar com revisionais de contratos e busca e apreensão.",
    author: "Dr. Marcelo Ribeiro",
    role: "Advogado Bancário",
    image: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    id: 206,
    category: "Cível e Bancário",
    quote: "A integração com os tribunais para captura de andamentos é muito eficiente.",
    author: "Dra. Laura Martins",
    role: "Advogada",
    image: "https://randomuser.me/api/portraits/women/11.jpg",
  },
  {
    id: 207,
    category: "Cível e Bancário",
    quote: "Consigo gerar relatórios de performance da carteira de processos com um clique.",
    author: "Dr. Eduardo Silva",
    role: "Sócio Diretor",
    image: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    id: 208,
    category: "Cível e Bancário",
    quote: "A Clausify transformou nosso contencioso cível de massa.",
    author: "Dra. Renata Costa",
    role: "Advogada Sênior",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: 209,
    category: "Cível e Bancário",
    quote: "Ferramenta robusta para cálculos de atualização monetária em execuções.",
    author: "Dr. Sérgio Alves",
    role: "Advogado",
    image: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    id: 210,
    category: "Cível e Bancário",
    quote: "A organização dos documentos probatórios é excelente para o direito do consumidor.",
    author: "Dra. Bianca Oliveira",
    role: "Especialista em Consumidor",
    image: "https://randomuser.me/api/portraits/women/13.jpg",
  },
  {
    id: 211,
    category: "Cível e Bancário",
    quote: "O sistema de tarefas ajuda muito a manter a equipe alinhada nos prazos fatais.",
    author: "Dr. Leonardo Souza",
    role: "Coordenador Jurídico",
    image: "https://randomuser.me/api/portraits/men/14.jpg",
  },
  {
    id: 212,
    category: "Cível e Bancário",
    quote: "Reduzimos drasticamente o número de revelias com o sistema de alertas.",
    author: "Dra. Mônica Lima",
    role: "Advogada",
    image: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    id: 213,
    category: "Cível e Bancário",
    quote: "A Clausify é parceira estratégica do nosso escritório na área bancária.",
    author: "Dr. Guilherme Santos",
    role: "Sócio",
    image: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    id: 214,
    category: "Cível e Bancário",
    quote: "Facilidade na gestão de acordos e pagamentos judiciais.",
    author: "Dra. Isabela Ferreira",
    role: "Advogada",
    image: "https://randomuser.me/api/portraits/women/15.jpg",
  },
  {
    id: 215,
    category: "Cível e Bancário",
    quote: "O suporte técnico é rápido e resolve qualquer dúvida sobre a plataforma.",
    author: "Dr. Daniel Costa",
    role: "Advogado",
    image: "https://randomuser.me/api/portraits/men/16.jpg",
  },
  {
    id: 216,
    category: "Cível e Bancário",
    quote: "Melhor investimento que fizemos para a gestão do contencioso cível.",
    author: "Dra. Paula Rocha",
    role: "Sócia Administradora",
    image: "https://randomuser.me/api/portraits/women/16.jpg",
  },
  {
    id: 217,
    category: "Cível e Bancário",
    quote: "A automação de contratos reduziu nosso tempo de revisão pela metade.",
    author: "Dr. Marcos Silva",
    role: "Advogado Cível",
    image: "https://randomuser.me/api/portraits/men/55.jpg",
  },
  {
    id: 218,
    category: "Cível e Bancário",
    quote: "Gestão de processos cíveis com eficiência e clareza. Recomendo.",
    author: "Dra. Fernanda Costa",
    role: "Advogada",
    image: "https://randomuser.me/api/portraits/women/55.jpg",
  },
  {
    id: 219,
    category: "Cível e Bancário",
    quote: "O painel de controle nos dá uma visão completa do contencioso de massa.",
    author: "Dr. Rafael Souza",
    role: "Gerente Jurídico",
    image: "https://randomuser.me/api/portraits/men/56.jpg",
  },
  {
    id: 220,
    category: "Cível e Bancário",
    quote: "Facilidade incrível para acompanhar publicações e andamentos.",
    author: "Dra. Beatriz Oliveira",
    role: "Advogada Plena",
    image: "https://randomuser.me/api/portraits/women/56.jpg",
  },
  {
    id: 221,
    category: "Cível e Bancário",
    quote: "A Clausify é indispensável para o nosso departamento jurídico.",
    author: "Dr. Thiago Lima",
    role: "Diretor Jurídico",
    image: "https://randomuser.me/api/portraits/men/57.jpg",
  },

  // --- Trabalhista (16 itens) ---
  {
    id: 301,
    category: "Trabalhista",
    quote: "Os cálculos trabalhistas automatizados da Clausify são precisos e economizam muito tempo.",
    author: "Dr. Carlos Eduardo",
    role: "Advogado Trabalhista",
    image: "https://randomuser.me/api/portraits/men/17.jpg",
  },
  {
    id: 302,
    category: "Trabalhista",
    quote: "Gerenciar audiências e prazos da CLT ficou muito mais fácil e seguro.",
    author: "Dra. Fernanda Souza",
    role: "Sócia - Trabalhista",
    image: "https://randomuser.me/api/portraits/women/17.jpg",
  },
  {
    id: 303,
    category: "Trabalhista",
    quote: "A plataforma ajuda muito na instrução processual e organização de provas.",
    author: "Dr. João Pedro",
    role: "Advogado Sênior",
    image: "https://randomuser.me/api/portraits/men/18.jpg",
  },
  {
    id: 304,
    category: "Trabalhista",
    quote: "Excelente para escritórios que atuam tanto para reclamante quanto para reclamada.",
    author: "Dra. Aline Moraes",
    role: "Advogada",
    image: "https://randomuser.me/api/portraits/women/18.jpg",
  },
  {
    id: 305,
    category: "Trabalhista",
    quote: "O controle de pautas de audiência é visual e evita conflitos de agenda.",
    author: "Dr. Rodrigo Lima",
    role: "Coordenador Trabalhista",
    image: "https://randomuser.me/api/portraits/men/19.jpg",
  },
  {
    id: 306,
    category: "Trabalhista",
    quote: "A Clausify nos permitiu escalar o atendimento a sindicatos com eficiência.",
    author: "Dra. Tatiane Silva",
    role: "Advogada Sindical",
    image: "https://randomuser.me/api/portraits/women/19.jpg",
  },
  {
    id: 307,
    category: "Trabalhista",
    quote: "Muito útil para calcular verbas rescisórias e estimar riscos processuais.",
    author: "Dr. Bruno Costa",
    role: "Advogado",
    image: "https://randomuser.me/api/portraits/men/20.jpg",
  },
  {
    id: 308,
    category: "Trabalhista",
    quote: "A gestão de documentos de RH dos clientes empresariais é facilitada.",
    author: "Dra. Camila Santos",
    role: "Consultora Trabalhista",
    image: "https://randomuser.me/api/portraits/women/20.jpg",
  },
  {
    id: 309,
    category: "Trabalhista",
    quote: "Otimizou nossa rotina de contencioso trabalhista de volume.",
    author: "Dr. Felipe Oliveira",
    role: "Sócio",
    image: "https://randomuser.me/api/portraits/men/21.jpg",
  },
  {
    id: 310,
    category: "Trabalhista",
    quote: "A interface limpa ajuda a focar no que importa: a defesa do cliente.",
    author: "Dra. Larissa Pereira",
    role: "Advogada",
    image: "https://randomuser.me/api/portraits/women/21.jpg",
  },
  {
    id: 311,
    category: "Trabalhista",
    quote: "Integração perfeita com nossa agenda de peritos e assistentes técnicos.",
    author: "Dr. Gustavo Rocha",
    role: "Advogado",
    image: "https://randomuser.me/api/portraits/men/22.jpg",
  },
  {
    id: 312,
    category: "Trabalhista",
    quote: "Reduzimos o tempo de elaboração de contestações com os modelos inteligentes.",
    author: "Dra. Marília Dias",
    role: "Advogada Plena",
    image: "https://randomuser.me/api/portraits/women/22.jpg",
  },
  {
    id: 313,
    category: "Trabalhista",
    quote: "A Clausify é essencial para o compliance trabalhista preventivo que oferecemos.",
    author: "Dr. Henrique Alves",
    role: "Consultor Jurídico",
    image: "https://randomuser.me/api/portraits/men/23.jpg",
  },
  {
    id: 314,
    category: "Trabalhista",
    quote: "Facilidade para acompanhar as constantes mudanças na legislação trabalhista.",
    author: "Dra. Sofia Martins",
    role: "Advogada",
    image: "https://randomuser.me/api/portraits/women/23.jpg",
  },
  {
    id: 315,
    category: "Trabalhista",
    quote: "O melhor software jurídico que já usei para a área trabalhista em 15 anos.",
    author: "Dr. Ricardo Ferreira",
    role: "Sócio Fundador",
    image: "https://randomuser.me/api/portraits/men/24.jpg",
  },
  {
    id: 316,
    category: "Trabalhista",
    quote: "Suporte ágil e funcionalidades que realmente atendem ao advogado trabalhista.",
    author: "Dra. Beatriz Lima",
    role: "Advogada",
    image: "https://randomuser.me/api/portraits/women/24.jpg",
  },
  {
    id: 317,
    category: "Trabalhista",
    quote: "Os cálculos de liquidação de sentença são precisos e rápidos.",
    author: "Dr. Bruno Silva",
    role: "Perito Trabalhista",
    image: "https://randomuser.me/api/portraits/men/60.jpg",
  },
  {
    id: 318,
    category: "Trabalhista",
    quote: "Controle total sobre os prazos de audiências e recursos trabalhistas.",
    author: "Dra. Juliana Costa",
    role: "Advogada Trabalhista",
    image: "https://randomuser.me/api/portraits/women/60.jpg",
  },
  {
    id: 319,
    category: "Trabalhista",
    quote: "A gestão de documentos de RH integrados é um grande diferencial.",
    author: "Dr. Rodrigo Almeida",
    role: "Consultor Jurídico",
    image: "https://randomuser.me/api/portraits/men/61.jpg",
  },
  {
    id: 320,
    category: "Trabalhista",
    quote: "Facilitou muito a nossa atuação em dissídios coletivos.",
    author: "Dra. Mariana Santos",
    role: "Advogada Sindical",
    image: "https://randomuser.me/api/portraits/women/61.jpg",
  },
  {
    id: 321,
    category: "Trabalhista",
    quote: "O suporte ao cliente é excepcional, sempre resolvendo nossas dúvidas.",
    author: "Dr. Lucas Oliveira",
    role: "Advogado",
    image: "https://randomuser.me/api/portraits/men/62.jpg",
  },

  // --- Empresarial e Tributário (16 itens) ---
  {
    id: 401,
    category: "Empresarial e Tributário",
    quote: "A gestão de teses tributárias e recuperação de créditos é potencializada pela Clausify.",
    author: "Dr. Alexandre Paiva",
    role: "Tributarista",
    image: "https://randomuser.me/api/portraits/men/25.jpg",
  },
  {
    id: 402,
    category: "Empresarial e Tributário",
    quote: "Controle societário e gestão de contratos empresariais em um só lugar.",
    author: "Dra. Helena Costa",
    role: "Advogada Corporativa",
    image: "https://randomuser.me/api/portraits/women/25.jpg",
  },
  {
    id: 403,
    category: "Empresarial e Tributário",
    quote: "Fundamental para o planejamento tributário e compliance fiscal dos nossos clientes.",
    author: "Dr. Vitor Mendes",
    role: "Sócio Tributário",
    image: "https://randomuser.me/api/portraits/men/26.jpg",
  },
  {
    id: 404,
    category: "Empresarial e Tributário",
    quote: "A análise de riscos contratuais com IA nos dá uma segurança jurídica enorme.",
    author: "Dra. Carolina Silva",
    role: "Gerente de Contratos",
    image: "https://randomuser.me/api/portraits/women/26.jpg",
  },
  {
    id: 405,
    category: "Empresarial e Tributário",
    quote: "Organização impecável para Due Diligence e fusões e aquisições (M&A).",
    author: "Dr. Fábio Rocha",
    role: "Advogado M&A",
    image: "https://randomuser.me/api/portraits/men/27.jpg",
  },
  {
    id: 406,
    category: "Empresarial e Tributário",
    quote: "Acompanhamento legislativo tributário em tempo real é um diferencial.",
    author: "Dra. Letícia Oliveira",
    role: "Consultora Tributária",
    image: "https://randomuser.me/api/portraits/women/27.jpg",
  },
  {
    id: 407,
    category: "Empresarial e Tributário",
    quote: "Facilita muito a gestão de certidões negativas e regularidade fiscal.",
    author: "Dr. Murilo Santos",
    role: "Advogado",
    image: "https://randomuser.me/api/portraits/men/28.jpg",
  },
  {
    id: 408,
    category: "Empresarial e Tributário",
    quote: "Plataforma robusta para lidar com grandes volumes de execuções fiscais.",
    author: "Dra. Renata Alves",
    role: "Advogada Sênior",
    image: "https://randomuser.me/api/portraits/women/28.jpg",
  },
  {
    id: 409,
    category: "Empresarial e Tributário",
    quote: "O CRM integrado ajuda a manter o relacionamento com clientes corporativos.",
    author: "Dr. André Lima",
    role: "Sócio",
    image: "https://randomuser.me/api/portraits/men/29.jpg",
  },
  {
    id: 410,
    category: "Empresarial e Tributário",
    quote: "Relatórios gerenciais detalhados que impressionam a diretoria das empresas clientes.",
    author: "Dra. Patrícia Gomes",
    role: "Advogada",
    image: "https://randomuser.me/api/portraits/women/29.jpg",
  },
  {
    id: 411,
    category: "Empresarial e Tributário",
    quote: "A Clausify modernizou nosso departamento jurídico interno.",
    author: "Dr. Thiago Costa",
    role: "Head Jurídico",
    image: "https://randomuser.me/api/portraits/men/30.jpg",
  },
  {
    id: 412,
    category: "Empresarial e Tributário",
    quote: "Eficiência na gestão de marcas e patentes e propriedade intelectual.",
    author: "Dra. Fernanda Dias",
    role: "Especialista em PI",
    image: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    id: 413,
    category: "Empresarial e Tributário",
    quote: "Segurança e confidencialidade garantidas para dados sensíveis de empresas.",
    author: "Dr. Lucas Ferreira",
    role: "Advogado",
    image: "https://randomuser.me/api/portraits/men/31.jpg",
  },
  {
    id: 414,
    category: "Empresarial e Tributário",
    quote: "A automação de fluxos de aprovação agilizou a assinatura de contratos.",
    author: "Dra. Marina Rocha",
    role: "Advogada",
    image: "https://randomuser.me/api/portraits/women/31.jpg",
  },
  {
    id: 415,
    category: "Empresarial e Tributário",
    quote: "Excelente custo-benefício para escritórios full-service empresariais.",
    author: "Dr. Eduardo Martins",
    role: "Sócio Administrador",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
  },
  {
    id: 416,
    category: "Empresarial e Tributário",
    quote: "A Clausify é a espinha dorsal da nossa operação jurídica tributária.",
    author: "Dra. Juliana Souza",
    role: "Sócia",
    image: "https://randomuser.me/api/portraits/women/32.jpg",
  },
  {
    id: 417,
    category: "Empresarial e Tributário",
    quote: "A due diligence nunca foi tão organizada e eficiente.",
    author: "Dr. Eduardo Silva",
    role: "Advogado Corporativo",
    image: "https://randomuser.me/api/portraits/men/65.jpg",
  },
  {
    id: 418,
    category: "Empresarial e Tributário",
    quote: "Gestão tributária complexa simplificada com a Clausify.",
    author: "Dra. Patrícia Costa",
    role: "Tributarista",
    image: "https://randomuser.me/api/portraits/women/65.jpg",
  },
  {
    id: 419,
    category: "Empresarial e Tributário",
    quote: "O controle de contratos empresariais é robusto e confiável.",
    author: "Dr. Gabriel Souza",
    role: "Gerente de Contratos",
    image: "https://randomuser.me/api/portraits/men/66.jpg",
  },
  {
    id: 420,
    category: "Empresarial e Tributário",
    quote: "Ferramenta vital para o compliance e governança corporativa.",
    author: "Dra. Luiza Lima",
    role: "Compliance Officer",
    image: "https://randomuser.me/api/portraits/women/66.jpg",
  },
  {
    id: 421,
    category: "Empresarial e Tributário",
    quote: "A análise de dados jurídicos impulsionou nossa estratégia de negócios.",
    author: "Dr. Rafael Ferreira",
    role: "Sócio Diretor",
    image: "https://randomuser.me/api/portraits/men/67.jpg",
  },

  // --- Previdenciário (16 itens) ---
  {
    id: 501,
    category: "Previdenciário",
    quote: "Os cálculos de RMI e tempo de contribuição são feitos em segundos. Fantástico.",
    author: "Dr. José Silva",
    role: "Advogado Previdenciário",
    image: "https://randomuser.me/api/portraits/men/33.jpg",
  },
  {
    id: 502,
    category: "Previdenciário",
    quote: "A gestão de prazos administrativos do INSS e judiciais é perfeita.",
    author: "Dra. Maria Oliveira",
    role: "Sócia - Previdência",
    image: "https://randomuser.me/api/portraits/women/33.jpg",
  },
  {
    id: 503,
    category: "Previdenciário",
    quote: "Importação automática do CNIS facilita demais a análise de direito.",
    author: "Dr. Antônio Costa",
    role: "Especialista em INSS",
    image: "https://randomuser.me/api/portraits/men/34.jpg",
  },
  {
    id: 504,
    category: "Previdenciário",
    quote: "A Clausify nos ajuda a identificar revisões de benefícios que passariam despercebidas.",
    author: "Dra. Sandra Lima",
    role: "Advogada",
    image: "https://randomuser.me/api/portraits/women/34.jpg",
  },
  {
    id: 505,
    category: "Previdenciário",
    quote: "Organização dos documentos médicos e laudos periciais é muito prática.",
    author: "Dr. Francisco Santos",
    role: "Advogado",
    image: "https://randomuser.me/api/portraits/men/35.jpg",
  },
  {
    id: 506,
    category: "Previdenciário",
    quote: "Ganhamos escala no escritório sem perder a qualidade no atendimento ao segurado.",
    author: "Dra. Ana Clara",
    role: "Sócia",
    image: "https://randomuser.me/api/portraits/women/35.jpg",
  },
  {
    id: 507,
    category: "Previdenciário",
    quote: "O sistema de CRM ajuda a manter o contato com clientes idosos ou com dificuldade.",
    author: "Dr. Pedro Alves",
    role: "Advogado",
    image: "https://randomuser.me/api/portraits/men/36.jpg",
  },
  {
    id: 508,
    category: "Previdenciário",
    quote: "Calculadoras previdenciárias sempre atualizadas com as últimas reformas.",
    author: "Dra. Luciana Rocha",
    role: "Advogada Sênior",
    image: "https://randomuser.me/api/portraits/women/36.jpg",
  },
  {
    id: 509,
    category: "Previdenciário",
    quote: "A automação de petições iniciais para benefícios por incapacidade é excelente.",
    author: "Dr. Ricardo Mendes",
    role: "Advogado",
    image: "https://randomuser.me/api/portraits/men/37.jpg",
  },
  {
    id: 510,
    category: "Previdenciário",
    quote: "Facilidade para acompanhar o resultado de perícias e recursos administrativos.",
    author: "Dra. Beatriz Ferreira",
    role: "Advogada",
    image: "https://randomuser.me/api/portraits/women/37.jpg",
  },
  {
    id: 511,
    category: "Previdenciário",
    quote: "A Clausify entende as dores do advogado previdenciarista.",
    author: "Dr. Luiz Carlos",
    role: "Sócio Fundador",
    image: "https://randomuser.me/api/portraits/men/38.jpg",
  },
  {
    id: 512,
    category: "Previdenciário",
    quote: "Melhorou muito nossa taxa de êxito nos processos de aposentadoria especial.",
    author: "Dra. Cláudia Silva",
    role: "Especialista",
    image: "https://randomuser.me/api/portraits/women/38.jpg",
  },
  {
    id: 513,
    category: "Previdenciário",
    quote: "O suporte nos ajuda muito com as dúvidas sobre os cálculos complexos.",
    author: "Dr. Fernando Oliveira",
    role: "Advogado",
    image: "https://randomuser.me/api/portraits/men/39.jpg",
  },
  {
    id: 514,
    category: "Previdenciário",
    quote: "Sistema leve, roda bem em qualquer computador, o que é ótimo para o dia a dia.",
    author: "Dra. Patrícia Lima",
    role: "Advogada",
    image: "https://randomuser.me/api/portraits/women/39.jpg",
  },
  {
    id: 515,
    category: "Previdenciário",
    quote: "Essencial para o planejamento previdenciário dos nossos clientes.",
    author: "Dr. Gabriel Santos",
    role: "Advogado",
    image: "https://randomuser.me/api/portraits/men/40.jpg",
  },
  {
    id: 516,
    category: "Previdenciário",
    quote: "Recomendo a Clausify para quem quer levar a advocacia previdenciária a sério.",
    author: "Dra. Renata Dias",
    role: "Sócia",
    image: "https://randomuser.me/api/portraits/women/40.jpg",
  },
  {
    id: 517,
    category: "Previdenciário",
    quote: "A simulação de aposentadoria é um recurso fantástico para o atendimento.",
    author: "Dr. Marcelo Dias",
    role: "Advogado Previdenciário",
    image: "https://randomuser.me/api/portraits/men/70.jpg",
  },
  {
    id: 518,
    category: "Previdenciário",
    quote: "Agilidade na análise de benefícios e revisão de vida toda.",
    author: "Dra. Carolina Nunes",
    role: "Especialista em INSS",
    image: "https://randomuser.me/api/portraits/women/70.jpg",
  },
  {
    id: 519,
    category: "Previdenciário",
    quote: "O sistema organiza todos os laudos e documentos do segurado perfeitamente.",
    author: "Dr. Felipe Santos",
    role: "Advogado",
    image: "https://randomuser.me/api/portraits/men/71.jpg",
  },
  {
    id: 520,
    category: "Previdenciário",
    quote: "Ganhamos muito tempo com a importação automática de dados do INSS.",
    author: "Dra. Vanessa Costa",
    role: "Sócia",
    image: "https://randomuser.me/api/portraits/women/71.jpg",
  },
  {
    id: 521,
    category: "Previdenciário",
    quote: "A Clausify é a parceira ideal para o advogado previdenciarista moderno.",
    author: "Dr. André Silva",
    role: "Advogado Sênior",
    image: "https://randomuser.me/api/portraits/men/72.jpg",
  },
]
